/*
Copyright 2017 Caicloud Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by set-gen. Do not edit it manually!

package cli

import (
	time "time"

	"github.com/spf13/cast"
)

// GetBool returns the value associated with the key as a bool.
func GetBool(key string) bool {
	return cast.ToBool(v.Get(key))
}

// GetDuration returns the value associated with the key as a time.Duration.
func GetDuration(key string) time.Duration {
	return cast.ToDuration(v.Get(key))
}

// GetFloat32 returns the value associated with the key as a float32.
func GetFloat32(key string) float32 {
	return cast.ToFloat32(v.Get(key))
}

// GetFloat64 returns the value associated with the key as a float64.
func GetFloat64(key string) float64 {
	return cast.ToFloat64(v.Get(key))
}

// GetInt returns the value associated with the key as a int.
func GetInt(key string) int {
	return cast.ToInt(v.Get(key))
}

// GetInt32 returns the value associated with the key as a int32.
func GetInt32(key string) int32 {
	return cast.ToInt32(v.Get(key))
}

// GetInt64 returns the value associated with the key as a int64.
func GetInt64(key string) int64 {
	return cast.ToInt64(v.Get(key))
}

// GetString returns the value associated with the key as a string.
func GetString(key string) string {
	return cast.ToString(v.Get(key))
}

// GetStringSlice returns the value associated with the key as a []string.
func GetStringSlice(key string) []string {
	return cast.ToStringSlice(v.Get(key))
}

// GetUint returns the value associated with the key as a uint.
func GetUint(key string) uint {
	return cast.ToUint(v.Get(key))
}

// GetUint32 returns the value associated with the key as a uint32.
func GetUint32(key string) uint32 {
	return cast.ToUint32(v.Get(key))
}

// GetUint64 returns the value associated with the key as a uint64.
func GetUint64(key string) uint64 {
	return cast.ToUint64(v.Get(key))
}
